minimumReleaseAge: 0
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

catalog:
  '@antfu/eslint-config': ^9.5.1
  '@eslint/compat': ^2.1.1
  '@eslint/config-helpers': ^0.7.0
  '@sveltejs/adapter-vercel': ^6.3.4
  '@sveltejs/kit': ^2.70.3
  '@sveltejs/vite-plugin-svelte': ^7.3.1
  '@types/node': ^26.6.3
  '@typescript-eslint/types': ^8.71.0
  eslint: ^10.11.0
  eslint-plugin-svelte: ^3.23.0
  globals: ^17.13.0
  hana-music-api: 1.4.0
  svelte: ^5.57.1
  svelte-check: ^4.7.6
  typescript: 6.0.3
  vite: ^8.3.2
