catalog:
  '@antfu/eslint-config': ^6.2.0
  '@eslint/compat': ^1.4.1
  '@libsql/client': ^0.15.15
  '@neoconfetti/svelte': ^2.2.2
  '@sveltejs/adapter-netlify': ^5.2.4
  '@sveltejs/enhanced-img': ^0.8.4
  '@sveltejs/kit': ^2.48.4
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@types/node': ^24.10.0
  '@types/throttle-debounce': ^5.0.2
  '@unocss/eslint-plugin': ^66.5.4
  '@unocss/preset-rem-to-px': ^66.5.4
  '@unocss/reset': ^66.5.4
  '@unocss/svelte-scoped': ^66.5.4
  autoprefixer: ^10.4.21
  csstype: ^3.1.3
  dayjs: ^1.11.19
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.6
  drizzle-orm: ^0.44.7
  eslint: ^9.39.1
  eslint-plugin-svelte: ^3.13.0
  globals: ^16.5.0
  lucide-svelte: ^0.552.0
  sass: ^1.93.3
  svelte: ^5.43.4
  svelte-check: ^4.3.3
  throttle-debounce: ^5.0.2
  typescript: ^5.9.3
  unocss: ^66.5.4
  unocss-preset-scrollbar: ^3.2.0
  vite: ^7.2.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
